version: '3.1'

services:
  db:
    container_name: leetcode-mysql-db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - leetcode-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

volumes:
  leetcode-volume:
    name: "leetcode-volume"